feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
]

# When coding this should be active, when site is live you disable this:
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import PostForm
from django.contrib import messages

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_thing'] = "Hello world :P this is dynamic"
        context['posts'] = Post.objects.all().order_by('-id') #by default this is ('i'), -i means descending
        return context

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post


class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/" # this goes back to the homepage

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Create a new Post
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    {% include "includes/navbar.html" %}
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %} bg-gradient text-center text-white py-4">
                <h3>{{ message }}</h3>
            </div>
        {% endfor %}
    {% endif %}
    
    <div class="container">
        {% block body %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}Detail view{% endblock %}

{% block body %}

<div class="row p-5">
    <h3 class="pb-2">{{ object.text }}</h3>
    <img src="{{ object.image.url }}" alt="" class="img-fluid" style="width: 100%; height: auto;">
    <a href="{% url 'feed:index' %}" class="py-5">&larr; Go back</a>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}My super awesome homepage{% endblock %}

{% block body %}

<div class="container">
    <div class="row text-center">
    {% for post in posts %}
        <div class="col-lg-3 col-md-6 col-sm-12 px-2">
            <div class="card my-4" style="width: 18rem;">
                {% thumbnail post.image "200x200" crop="center" as im %}
                    <img src="{{ im.url }}" class="card-img-top img-fluid" alt="...">
                {% endthumbnail %}
                <div class="card-body">
                    <p class="card-text">{{ post.text }}</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Image</a>
                </div>
            </div>
        </div>
    


    {% empty %}
        <div class="col-sm-6 offset-3 text-center py-5 my-5">
            <h2 class="p-2">Welcome!</h2>
            <p class="p-2">Add your first image maybe?</p>
            <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload Image</a>
        </div>     
    {% endfor %}
    </div>
</div>

{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <section class="fs-5">IMAGE SHARER</section>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav px-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Add New Image</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %}Upload a new image{% endblock %}

{% block body %}
    <div class="row pt-5">
        <form action="" method="POST" enctype="multipart/form-data" class="col-sm-4 offset-4">
            <h2 class="p-5">Upload an image</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <div class="p-5">
                <button type="submit" class="btn btn-success">
                    Upload Image
                </button>
            </div>
        </form>
    </div>
    
{% endblock %}